import Head from "next/head";
import { Button, FloatButton, Image, Progress } from "antd";
import Navbar from "../components/Navbar";
import { AuthProvider } from "../context/AuthContext";
import Footer from "../components/Footer";
import Link from "next/link";
import ChartData from "../components/ChartData";

export default function Home() {
  const options = {
    responsive: false,
    plugins: {
      legend: {
        display: false
      },
      title: {
        display: false,
      },
    },
  };

  const labels = [
    "6月",
    "7月",
    "8月",
    "9月",
    "10月",
    "11月",
    "12月",
    "1月",
    "2月",
    "3月",
    "4月",
    "5月",
  ];

  const chartData = {
    labels,
    datasets: [
      {
        label: "Dataset 1",
        data: labels.map(() => Math.random()),
        borderColor: "#8FE9D0",
        backgroundColor: "#8FE9D0",
      },
      {
        label: "Dataset 2",
        data: labels.map(() => Math.random()),
        borderColor: "#FFCC21",
        backgroundColor: "#FFCC21",
      },
    ],
  };

  const contentMenu = [
    {
      title: 'Morning',
      icon: <Image src="/static/images/icon_knife.png" width={56} height={56} preview={false} />,
      url: ''
    },
    {
      title: 'Lunch',
      icon: <Image src="/static/images/icon_knife.png" width={56} height={56} preview={false} />,
      url: ''
    },
    {
      title: 'Dinner',
      icon: <Image src="/static/images/icon_knife.png" width={56} height={56} preview={false} />,
      url: ''
    },
    {
      title: 'Snack',
      icon: <Image src="/static/images/icon_cup.png" width={56} height={56} preview={false} />,
      url: ''
    },
  ]

  const gallery = [
    {
      label: '05.21.Morning',
      image: <Image src="/static/images/m01.jpg" width="100%" height="100%" preview={false} />,
      url: ''
    },
    {
      label: '05.21.Lunch',
      image: <Image src="/static/images/l03.jpg" width="100%" height="100%" preview={false} />,
      url: ''
    },
    {
      label: '05.21.Dinner',
      image: <Image src="/static/images/d01.jpg" width="100%" height="100%" preview={false} />,
      url: ''
    },
    {
      label: '05.21.Snack',
      image: <Image src="/static/images/l01.jpg" width="100%" height="100%" preview={false} />,
      url: ''
    },
    {
      label: '05.20.Morning',
      image: <Image src="/static/images/m01.jpg" width="100%" height="100%" preview={false} />,
      url: ''
    },
    {
      label: '05.20.Lunch',
      image: <Image src="/static/images/l02.jpg" width="100%" height="100%" preview={false} />,
      url: ''
    },
    {
      label: '05.20.Dinner',
      image: <Image src="/static/images/d02.jpg" width="100%" height="100%" preview={false} />,
      url: ''
    },
    {
      label: '05.21.Snack',
      image: <Image src="/static/images/s01.jpg" width="100%" height="100%" preview={false} />,
      url: ''
    },
  ]

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <AuthProvider>
          <section className="grid grid-cols-3 mt-[64px]">
            <div className="col-span-1 relative h-[316px] bg-[url('/static/images/d01.jpg')]">
              <div className="absolute top-[50%] left-[50%] -translate-x-1/2 -translate-y-1/2">
                <Progress
                  type="circle"
                  percent={75}
                  className="z-10"
                  trailColor="#ffffff00"
                  strokeColor="#ffffff"
                  width={150}
                  format={(percent) => {
                    return (
                      <p className="text-white text-lg">
                        05/12{" "}
                        <span className="text-white text-3xl">{percent}%</span>
                      </p>
                    );
                  }}
                />
              </div>
            </div>
            <div className="col-span-2 bg-[#2E2E2E] max-h-[316px]">
              <div className="w-[90%] mx-auto text-white pt-[4px] flex justify-center items-center">
                <ChartData
                  options={options}
                  chartData={chartData}
                  styles={{ height: "308px", width: "90%" }}
                />
              </div>
            </div>
          </section>

          <section className="w-[80%] mx-auto py-[55px]">
            <section className="grid grid-cols-4 gap-4">
              {contentMenu.map((item, index) => {
                return (
                  <div
                    key={index}
                    className="relative flex flex-row justify-center items-center"
                  >
                    <Image
                      src="/static/images/hexagon.png"
                      width={134}
                      height={134}
                      preview={false}
                    />
                    <Link href={item.url}>
                      <a className="flex flex-col justify-center items-center absolute">
                        {item.icon}
                        <p className={`mb-0 text-white text-2xl`}>{item.title}</p>
                      </a>
                    </Link>
                  </div>
                );
              })}
            </section>

            <section className="grid grid-cols-4 gap-4 mt-[25px]">
              {gallery.map((item, index) => {
                return (
                  <div key={index} className="relative">
                    {item.image}
                    <Link href={item.url}>
                      <a className="block bg-light-orange text-white text-center px-[8px] py-[7px] absolute bottom-0 left-0">
                        {item.label}
                      </a>
                    </Link>
                  </div>
                );
              })}
            </section>

            <section className="flex justify-center items-center mb-[64px]">
              <Link href='/records'>
                <Button
                  className="text-white mt-[28px] w-[296px] h-[56px] border-0 text-lg font-hiragino"
                  style={{
                    background:
                      "linear-gradient(32.95deg, #FFCC21 8.75%, #FF963C 86.64%)",
                  }}
                >
                  記録をもっと見る
                </Button>
              </Link>
            </section>
          </section>
        </AuthProvider>

        <FloatButton.BackTop />
      </main>

      <Footer />
    </div>
  );
}
