import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import { AuthProvider } from '../context/AuthContext'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <AuthProvider>
          <Navbar />
          <Image src="/static/images/column-1.jpg" alt="Vercel Logo" width={80} height={80} />
        </AuthProvider>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
